version: '3'

services:
  api: &api
    build:
      context: .
      dockerfile: compose/prod/Dockerfile
    command: bash -c "
        cd src
        && ./manage.py migrate
        && gunicorn core.wsgi:application -c core/gunicorn.conf.py --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - compose/prod/.env
    depends_on:
      - redis
      - pg

  celeryworker:
    <<: *api
    command: bash -c "
      cd src/
      && celery -A core.celery worker -l info"
    ports: []

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

  pg:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

volumes:
  redis-data:
  pg-data:
